apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schedule-app
  name: schedule-app
spec:
  replicas: 3
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: schedule-app
  template:
    metadata:
      labels:
        app: schedule-app
    spec:
      containers:
      - image: jjmmyyou111/schedule-app:latest
        name: schedule-app
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: 'redis://redis:6379'
        - name: MYSQL_HOST
          value: mysql-service
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: '1111'
        - name: foo
          value: bar
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service
  labels:
    app: schedule-app
spec:
  ports:
  - nodePort: 32391
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: schedule-app
  type: LoadBalancer
