default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  username: root
  password: '1111'
  host: 127.0.0.1
  port: 3306
  secure_auth: false

development:
  <<: *default
  database: study_development

test:
  <<: *default
  database: study_test

production:
  <<: *default
  database: study_production
