default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306
  secure_auth: false

development:
  <<: *default
  database: study_development

test:
  <<: *default
  database: study_test

production:
  <<: *default
  database: study_production
